version: '3'
services:
  server:
    build: ./server
    ports:
      - 3000:3000
    networks:
      - mynetwork

  client:
    build: ./client
    ports:
      - 8000:8000
    networks:
      - mynetwork
    depends_on:
      - serviceName: server
        

networks:
  mynetwork:
